using KingFashion.Commons;
using KingFashionWeb.Helpers;
using KingFashionWeb.Models;
using KingFashionWeb.Models.Category;
using KingFashionWeb.Models.Order;
using KingFashionWeb.Models.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KingFashionWeb.Controllers
{
    public class ShopController : Controller
    {
        private readonly ILogger<ShopController> _logger;
        public ShopController(ILogger<ShopController> logger)
        {
            _logger = logger;
        }
        //[Route("")]
        //[Route("/Shop/ViewShop")]
        public IActionResult Index()
        {
            ShopAll shopAll = new ShopAll();
            shopAll.Categories = JsonConvert.DeserializeObject<List<CategoryView>>("[{\"Id\":1,\"Title\":\"Cate1\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":2,\"Title\":\"Cate2\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":3,\"Title\":\"Cate3\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":4,\"Title\":\"Cate4\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":5,\"Title\":\"Cate5\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":6,\"Title\":\"Cate5\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"}]");
            shopAll.Products = JsonConvert.DeserializeObject<List<ProductView>>("[{\"Id\":1,\"CategoryId\":1,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":2,\"CategoryId\":1,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":3,\"CategoryId\":2,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":4,\"CategoryId\":2,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":5,\"CategoryId\":3,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":6,\"CategoryId\":3,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":7,\"CategoryId\":4,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":8,\"CategoryId\":4,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":9,\"CategoryId\":5,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":10,\"CategoryId\":5,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":11,\"CategoryId\":6,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":12,\"CategoryId\":6,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true}]");
            shopAll.viewOrders = JsonConvert.DeserializeObject<List<ViewOrder>>("[\r\n{\r\n\"Id\":1,\r\n\"UserId\":1,\r\n\"SessionId\":\"productname1\",\r\n\"Token\":\"productname1\",\r\n\"Status\":1,\r\n\"SubTotal\":1,\r\n\"ItemDiscount\":1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\":1,\r\n\"Promo\":\"string\",\r\n\"Discount\":1,\r\n\"GrandTotal\":1,\r\n\"FirstName\":\"string\",\r\n\"MiddleName\":\"string\",\r\n\"LastName\":\"string\",\r\n\"Mobile\":\"string\",\r\n\"Email\": \"string\",\r\n\"Line1\":\"string\",\r\n\"Line2\":\"string\",\r\n\"City\":\"string\",\r\n\"Province\":\"string\",\r\n\"Country\":\"string\",\r\n\"CreatedAt\":\"1995-04-07T00:00:00\",\r\n\"UpdatedAt\":\"1995-04-07T00:00:00\",\r\n\"Content\": \"string\"\r\n},\r\n{\r\n\"Id\": 2,\r\n\"UserId\": 2,\r\n\"SessionId\": \"productname2\",\r\n\"Token\":\"productname2\",\r\n\"Status\":1,\r\n\"SubTotal\": 1,\r\n\"ItemDiscount\": 1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\": 1,\r\n\"Promo\":\"string\",\r\n    \"Discount\": 1,\r\n    \"GrandTotal\": 1,\r\n    \"FirstName\": \"string\",\r\n    \"MiddleName\": \"string\",\r\n    \"LastName\": \"string\",\r\n    \"Mobile\": \"string\",\r\n    \"Email\": \"string\",\r\n    \"Line1\": \"string\",\r\n    \"Line2\": \"string\",\r\n    \"City\": \"string\",\r\n    \"Province\": \"string\",\r\n    \"Country\": \"string\",\r\n    \"CreatedAt\": \"1995-04-07T00:00:00\",\r\n\"UpdatedAt\": \"1995-04-07T00:00:00\",\r\n\"Content\":\"string\"\r\n},\r\n{\r\n\"Id\":3,\r\n\"UserId\": 3,\r\n\"SessionId\":\"productname3\",\r\n\"Token\": \"productname3\",\r\n\"Status\": 1,\r\n\"SubTotal\": 1,\r\n\"ItemDiscount\":1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\":1,\r\n\"Promo\":\"string\",\r\n\"Discount\":1,\r\n\"GrandTotal\":1,\r\n\"FirstName\":\"string\",\r\n\"MiddleName\":\"string\",\r\n\"LastName\":\"string\",\r\n\"Mobile\":\"string\",\r\n\"Email\": \"string\",\r\n\"Line1\":\"string\",\r\n\"Line2\":\"string\",\r\n\"City\":\"string\",\r\n\"Province\":\"string\",\r\n\"Country\":\"string\",\r\n\"CreatedAt\":\"1995-04-07T00:00:00\",\r\n\"UpdatedAt\":\"1995-04-07T00:00:00\",\r\n\"Content\":\"string\"\r\n}\r\n]");
            //ApiHelper.HttpGet<List<CategoryView>>(@$"{Common.ApiUrl}Category");
            return View(shopAll);
        }
        public IActionResult Contact()
        {
            ShopAll shopAll = new ShopAll();
            shopAll.Categories = JsonConvert.DeserializeObject<List<CategoryView>>("[{\"Id\":1,\"Title\":\"Cate1\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":2,\"Title\":\"Cate2\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":3,\"Title\":\"Cate3\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":4,\"Title\":\"Cate4\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":5,\"Title\":\"Cate5\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":6,\"Title\":\"Cate5\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"}]");
            shopAll.Products = JsonConvert.DeserializeObject<List<ProductView>>("[{\"Id\":1,\"CategoryId\":1,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":2,\"CategoryId\":1,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":3,\"CategoryId\":2,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":4,\"CategoryId\":2,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":5,\"CategoryId\":3,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":6,\"CategoryId\":3,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":7,\"CategoryId\":4,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":8,\"CategoryId\":4,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":9,\"CategoryId\":5,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":10,\"CategoryId\":5,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":11,\"CategoryId\":6,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":12,\"CategoryId\":6,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true}]");
            shopAll.viewOrders = JsonConvert.DeserializeObject<List<ViewOrder>>("[\r\n{\r\n\"Id\":1,\r\n\"UserId\":1,\r\n\"SessionId\":\"productname1\",\r\n\"Token\":\"productname1\",\r\n\"Status\":1,\r\n\"SubTotal\":1,\r\n\"ItemDiscount\":1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\":1,\r\n\"Promo\":\"string\",\r\n\"Discount\":1,\r\n\"GrandTotal\":1,\r\n\"FirstName\":\"string\",\r\n\"MiddleName\":\"string\",\r\n\"LastName\":\"string\",\r\n\"Mobile\":\"string\",\r\n\"Email\": \"string\",\r\n\"Line1\":\"string\",\r\n\"Line2\":\"string\",\r\n\"City\":\"string\",\r\n\"Province\":\"string\",\r\n\"Country\":\"string\",\r\n\"CreatedAt\":\"1995-04-07T00:00:00\",\r\n\"UpdatedAt\":\"1995-04-07T00:00:00\",\r\n\"Content\": \"string\"\r\n},\r\n{\r\n\"Id\": 2,\r\n\"UserId\": 2,\r\n\"SessionId\": \"productname2\",\r\n\"Token\":\"productname2\",\r\n\"Status\":1,\r\n\"SubTotal\": 1,\r\n\"ItemDiscount\": 1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\": 1,\r\n\"Promo\":\"string\",\r\n    \"Discount\": 1,\r\n    \"GrandTotal\": 1,\r\n    \"FirstName\": \"string\",\r\n    \"MiddleName\": \"string\",\r\n    \"LastName\": \"string\",\r\n    \"Mobile\": \"string\",\r\n    \"Email\": \"string\",\r\n    \"Line1\": \"string\",\r\n    \"Line2\": \"string\",\r\n    \"City\": \"string\",\r\n    \"Province\": \"string\",\r\n    \"Country\": \"string\",\r\n    \"CreatedAt\": \"1995-04-07T00:00:00\",\r\n\"UpdatedAt\": \"1995-04-07T00:00:00\",\r\n\"Content\":\"string\"\r\n},\r\n{\r\n\"Id\":3,\r\n\"UserId\": 3,\r\n\"SessionId\":\"productname3\",\r\n\"Token\": \"productname3\",\r\n\"Status\": 1,\r\n\"SubTotal\": 1,\r\n\"ItemDiscount\":1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\":1,\r\n\"Promo\":\"string\",\r\n\"Discount\":1,\r\n\"GrandTotal\":1,\r\n\"FirstName\":\"string\",\r\n\"MiddleName\":\"string\",\r\n\"LastName\":\"string\",\r\n\"Mobile\":\"string\",\r\n\"Email\": \"string\",\r\n\"Line1\":\"string\",\r\n\"Line2\":\"string\",\r\n\"City\":\"string\",\r\n\"Province\":\"string\",\r\n\"Country\":\"string\",\r\n\"CreatedAt\":\"1995-04-07T00:00:00\",\r\n\"UpdatedAt\":\"1995-04-07T00:00:00\",\r\n\"Content\":\"string\"\r\n}\r\n]");
            //ApiHelper.HttpGet<List<CategoryView>>(@$"{Common.ApiUrl}Category");
            return View(shopAll);

        }
        public IActionResult ViewShop()
        {
            ShopAll shopAll = new ShopAll();
            shopAll.Categories = JsonConvert.DeserializeObject<List<CategoryView>>("[{\"Id\":1,\"Title\":\"Cate1\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":2,\"Title\":\"Cate2\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":3,\"Title\":\"Cate3\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":4,\"Title\":\"Cate4\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":5,\"Title\":\"Cate5\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":6,\"Title\":\"Cate5\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"}]");
            shopAll.Products = JsonConvert.DeserializeObject<List<ProductView>>("[{\"Id\":1,\"CategoryId\":1,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":2,\"CategoryId\":1,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":3,\"CategoryId\":2,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":4,\"CategoryId\":2,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":5,\"CategoryId\":3,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":6,\"CategoryId\":3,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":7,\"CategoryId\":4,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":8,\"CategoryId\":4,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":9,\"CategoryId\":5,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":10,\"CategoryId\":5,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":11,\"CategoryId\":6,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":12,\"CategoryId\":6,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true}]");
            shopAll.viewOrders = JsonConvert.DeserializeObject<List<ViewOrder>>("[\r\n{\r\n\"Id\":1,\r\n\"UserId\":1,\r\n\"SessionId\":\"productname1\",\r\n\"Token\":\"productname1\",\r\n\"Status\":1,\r\n\"SubTotal\":1,\r\n\"ItemDiscount\":1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\":1,\r\n\"Promo\":\"string\",\r\n\"Discount\":1,\r\n\"GrandTotal\":1,\r\n\"FirstName\":\"string\",\r\n\"MiddleName\":\"string\",\r\n\"LastName\":\"string\",\r\n\"Mobile\":\"string\",\r\n\"Email\": \"string\",\r\n\"Line1\":\"string\",\r\n\"Line2\":\"string\",\r\n\"City\":\"string\",\r\n\"Province\":\"string\",\r\n\"Country\":\"string\",\r\n\"CreatedAt\":\"1995-04-07T00:00:00\",\r\n\"UpdatedAt\":\"1995-04-07T00:00:00\",\r\n\"Content\": \"string\"\r\n},\r\n{\r\n\"Id\": 2,\r\n\"UserId\": 2,\r\n\"SessionId\": \"productname2\",\r\n\"Token\":\"productname2\",\r\n\"Status\":1,\r\n\"SubTotal\": 1,\r\n\"ItemDiscount\": 1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\": 1,\r\n\"Promo\":\"string\",\r\n    \"Discount\": 1,\r\n    \"GrandTotal\": 1,\r\n    \"FirstName\": \"string\",\r\n    \"MiddleName\": \"string\",\r\n    \"LastName\": \"string\",\r\n    \"Mobile\": \"string\",\r\n    \"Email\": \"string\",\r\n    \"Line1\": \"string\",\r\n    \"Line2\": \"string\",\r\n    \"City\": \"string\",\r\n    \"Province\": \"string\",\r\n    \"Country\": \"string\",\r\n    \"CreatedAt\": \"1995-04-07T00:00:00\",\r\n\"UpdatedAt\": \"1995-04-07T00:00:00\",\r\n\"Content\":\"string\"\r\n},\r\n{\r\n\"Id\":3,\r\n\"UserId\": 3,\r\n\"SessionId\":\"productname3\",\r\n\"Token\": \"productname3\",\r\n\"Status\": 1,\r\n\"SubTotal\": 1,\r\n\"ItemDiscount\":1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\":1,\r\n\"Promo\":\"string\",\r\n\"Discount\":1,\r\n\"GrandTotal\":1,\r\n\"FirstName\":\"string\",\r\n\"MiddleName\":\"string\",\r\n\"LastName\":\"string\",\r\n\"Mobile\":\"string\",\r\n\"Email\": \"string\",\r\n\"Line1\":\"string\",\r\n\"Line2\":\"string\",\r\n\"City\":\"string\",\r\n\"Province\":\"string\",\r\n\"Country\":\"string\",\r\n\"CreatedAt\":\"1995-04-07T00:00:00\",\r\n\"UpdatedAt\":\"1995-04-07T00:00:00\",\r\n\"Content\":\"string\"\r\n}\r\n]");
            //ApiHelper.HttpGet<List<CategoryView>>(@$"{Common.ApiUrl}Category");
            return View(shopAll);
        }
        public IActionResult ShoppingCart()
        {

            ShopAll shopAll = new ShopAll();
            shopAll.Categories = JsonConvert.DeserializeObject<List<CategoryView>>("[{\"Id\":1,\"Title\":\"Cate1\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":2,\"Title\":\"Cate2\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":3,\"Title\":\"Cate3\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":4,\"Title\":\"Cate4\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":5,\"Title\":\"Cate5\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"},{\"Id\":6,\"Title\":\"Cate5\",\"MetaTitle\":\"\",\"Slug\":\"mi-an-lien-omachi-khoai-tay-suon-ham-ngu-qua-30goi\"}]");
            shopAll.Products = JsonConvert.DeserializeObject<List<ProductView>>("[{\"Id\":1,\"CategoryId\":1,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":2,\"CategoryId\":1,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":3,\"CategoryId\":2,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":4,\"CategoryId\":2,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":5,\"CategoryId\":3,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":6,\"CategoryId\":3,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":7,\"CategoryId\":4,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":8,\"CategoryId\":4,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":9,\"CategoryId\":5,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":10,\"CategoryId\":5,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":11,\"CategoryId\":6,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true},{\"Id\":12,\"CategoryId\":6,\"Title\":\"productname1\",\"MetaTitle\":\"productname1\",\"Slug\":\"productname1\",\"Summary\":\"productname1\",\"Type\":1,\"SKU\":\"productname1\",\"Price\":1,\"Discount\":1,\"Shop\":true}]");
            shopAll.viewOrders = JsonConvert.DeserializeObject<List<ViewOrder>>("[\r\n{\r\n\"Id\":1,\r\n\"UserId\":1,\r\n\"SessionId\":\"productname1\",\r\n\"Token\":\"productname1\",\r\n\"Status\":1,\r\n\"SubTotal\":1,\r\n\"ItemDiscount\":1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\":1,\r\n\"Promo\":\"string\",\r\n\"Discount\":1,\r\n\"GrandTotal\":1,\r\n\"FirstName\":\"string\",\r\n\"MiddleName\":\"string\",\r\n\"LastName\":\"string\",\r\n\"Mobile\":\"string\",\r\n\"Email\": \"string\",\r\n\"Line1\":\"string\",\r\n\"Line2\":\"string\",\r\n\"City\":\"string\",\r\n\"Province\":\"string\",\r\n\"Country\":\"string\",\r\n\"CreatedAt\":\"1995-04-07T00:00:00\",\r\n\"UpdatedAt\":\"1995-04-07T00:00:00\",\r\n\"Content\": \"string\"\r\n},\r\n{\r\n\"Id\": 2,\r\n\"UserId\": 2,\r\n\"SessionId\": \"productname2\",\r\n\"Token\":\"productname2\",\r\n\"Status\":1,\r\n\"SubTotal\": 1,\r\n\"ItemDiscount\": 1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\": 1,\r\n\"Promo\":\"string\",\r\n    \"Discount\": 1,\r\n    \"GrandTotal\": 1,\r\n    \"FirstName\": \"string\",\r\n    \"MiddleName\": \"string\",\r\n    \"LastName\": \"string\",\r\n    \"Mobile\": \"string\",\r\n    \"Email\": \"string\",\r\n    \"Line1\": \"string\",\r\n    \"Line2\": \"string\",\r\n    \"City\": \"string\",\r\n    \"Province\": \"string\",\r\n    \"Country\": \"string\",\r\n    \"CreatedAt\": \"1995-04-07T00:00:00\",\r\n\"UpdatedAt\": \"1995-04-07T00:00:00\",\r\n\"Content\":\"string\"\r\n},\r\n{\r\n\"Id\":3,\r\n\"UserId\": 3,\r\n\"SessionId\":\"productname3\",\r\n\"Token\": \"productname3\",\r\n\"Status\": 1,\r\n\"SubTotal\": 1,\r\n\"ItemDiscount\":1,\r\n\"Tax\":1,\r\n\"Shipping\":1,\r\n\"Total\":1,\r\n\"Promo\":\"string\",\r\n\"Discount\":1,\r\n\"GrandTotal\":1,\r\n\"FirstName\":\"string\",\r\n\"MiddleName\":\"string\",\r\n\"LastName\":\"string\",\r\n\"Mobile\":\"string\",\r\n\"Email\": \"string\",\r\n\"Line1\":\"string\",\r\n\"Line2\":\"string\",\r\n\"City\":\"string\",\r\n\"Province\":\"string\",\r\n\"Country\":\"string\",\r\n\"CreatedAt\":\"1995-04-07T00:00:00\",\r\n\"UpdatedAt\":\"1995-04-07T00:00:00\",\r\n\"Content\":\"string\"\r\n}\r\n]");
            //ApiHelper.HttpGet<List<CategoryView>>(@$"{Common.ApiUrl}Category");
            return View(shopAll);
        }
    }   
}
